# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            "IREC 2019"
tagline:          "A SEDS-UCF project."
description:      "SEDS-UCF's 2019 IREC project log."
url:              http://irec19.sedsucf.org/
baseurl:          /

author:
  name:           'SEDS-UCF'
  url:            http://sedsucf.org/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      comments: false
      excerpt_separator: <!--more-->

# Custom vars
#version:            3.5.3
sidebar_home_link:  false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
#github:
#  repo:             https://github.com/fongandrew/hydeout
