# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            IREC 2018 Log
tagline:          'A SEDS-UCF project.'
description:      'A log for the SEDS-UCF 2018 IREC project.'
url:              https://seds-ucf.github.io
baseurl:          /irec2018-project-log

author:
  name:           'SEDS-UCF'
  url:            http://www.mae.ucf.edu/mmae/seds/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
#version:            3.5.3
sidebar_home_link:  false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
#github:
#  repo:             https://github.com/fongandrew/hydeout
